name: Release

# 定义触发条件：在 main 分支推送或手动触发工作流
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # Windows 端打包
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. 设置 Node.js 版本
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 3. 安装项目依赖
      - name: Install dependencies
        run: npm install

      # 4. 运行通用的构建命令
      - name: Run common build
        run: npm run build

      # 5. 针对 Windows 的专用构建
      - name: Run Windows build
        run: npm run electron:build:win 

      # 6. 重命名 Windows 构建产物为动态版本号
      - name: Rename Windows artifact
        run: |
          mv "./dist_electron/MoeKoe Music Setup 1.0.0.exe" "./dist_electron/MoeKoe_Music_Setup_${{ env.NEW_VERSION }}.exe"

      # 7. 上传重命名后的 Windows 构建产物到 GitHub Actions 以便后续使用
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-win
          path: ./dist_electron/MoeKoe_Music_Setup_${{ env.NEW_VERSION }}.exe

  # macOS 端打包
  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run common build
        run: npm run build

      - name: Run macOS build
        run: npm run electron:build:macos

      - name: Rename macOS artifacts
        run: |
          mv "./dist_electron/MoeKoe Music-1.0.0-arm64.dmg" "./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}-arm64.dmg"
          mv "./dist_electron/MoeKoe Music-1.0.0-arm64-mac.zip" "./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}-arm64-mac.zip"

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: app-macos-dmg
          path: ./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}-arm64.dmg

      - name: Upload macOS ZIP
        uses: actions/upload-artifact@v4
        with:
          name: app-macos-zip
          path: ./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}-arm64-mac.zip

  # Linux 端打包
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run common build
        run: npm run build

      - name: Run Linux build
        run: npm run electron:build:linux

      - name: Rename Linux artifacts
        run: |
          mv "./dist_electron/MoeKoe Music-1.0.0.AppImage" "./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}.AppImage"
          mv "./dist_electron/moekoemusic_1.0.0_amd64.deb" "./dist_electron/moekoemusic_${{ env.NEW_VERSION }}_amd64.deb"

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: |
            ./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}.AppImage
            ./dist_electron/moekoemusic_${{ env.NEW_VERSION }}_amd64.deb

  # 创建 GitHub Release
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment version
        id: create_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print}')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      # 提取最新提交信息作为发布说明
      - name: Get latest commit message
        id: get_commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}-Beta
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "Release ${{ env.NEW_VERSION }}"
          body: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: true
          files: |
            ./dist_electron/MoeKoe_Music_Setup_${{ env.NEW_VERSION }}.exe
            ./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}-arm64.dmg
            ./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}-arm64-mac.zip
            ./dist_electron/MoeKoe_Music_${{ env.NEW_VERSION }}.AppImage
            ./dist_electron/moekoemusic_${{ env.NEW_VERSION }}_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}